name: ML API CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install pytest pytest-cov fastapi uvicorn pandas scikit-learn sqlalchemy psycopg2-binary joblib httpx

      - name: Set CI environment
        run: echo "CI=true" >> $GITHUB_ENV

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Run tests with coverage
        run: |
          pytest \
          --cov=app \
          --cov=code \
          --cov-report=term-missing


  deploy_space:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          echo "=== CLONE HF SPACE ==="
          git clone https://oauth2:${HF_TOKEN}@huggingface.co/spaces/maximilien777/Projet5_ml_api hf_space

          echo "=== COPY FILES ==="
          cp -r app hf_space/
          cp -r models hf_space/
          cp pyproject.toml hf_space/

          cd hf_space

          echo "=== ADD ==="
          git add .

          echo "=== COMMIT ==="
          git commit -m "auto deploy" || echo "NO CHANGES TO COMMIT"

          echo "=== PUSH ==="
          git push
